# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\git\esaa\EsIDAUtils\EsIDAUtils\ui\matrix_editor.ui'
#
# Created: Tue Nov 15 12:55:39 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_matrix_editor(object):
    def setupUi(self, matrix_editor):
        matrix_editor.setObjectName("matrix_editor")
        matrix_editor.resize(945, 565)
        self.horizontalLayout = QtGui.QHBoxLayout(matrix_editor)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.categoryTree = QtGui.QTreeWidget(matrix_editor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.categoryTree.sizePolicy().hasHeightForWidth())
        self.categoryTree.setSizePolicy(sizePolicy)
        self.categoryTree.setMinimumSize(QtCore.QSize(300, 0))
        self.categoryTree.setObjectName("categoryTree")
        self.categoryTree.headerItem().setText(0, "1")
        self.categoryTree.header().setVisible(False)
        self.horizontalLayout.addWidget(self.categoryTree)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(matrix_editor)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.nameEdit = QtGui.QLineEdit(matrix_editor)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.nameEdit)
        self.label_8 = QtGui.QLabel(matrix_editor)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.sizeComboBox = QtGui.QComboBox(matrix_editor)
        self.sizeComboBox.setObjectName("sizeComboBox")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.sizeComboBox)
        self.label_4 = QtGui.QLabel(matrix_editor)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.addrEdit = QtGui.QLineEdit(matrix_editor)
        self.addrEdit.setObjectName("addrEdit")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.addrEdit)
        self.label_11 = QtGui.QLabel(matrix_editor)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_11)
        self.groupBox = QtGui.QGroupBox(matrix_editor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.axisXComboBox = QtGui.QComboBox(self.groupBox)
        self.axisXComboBox.setObjectName("axisXComboBox")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.axisXComboBox)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.axisXAddrEdit = QtGui.QLineEdit(self.groupBox)
        self.axisXAddrEdit.setObjectName("axisXAddrEdit")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.axisXAddrEdit)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.countXEdit = QtGui.QLineEdit(self.groupBox)
        self.countXEdit.setObjectName("countXEdit")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.countXEdit)
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.groupBox)
        self.label_12 = QtGui.QLabel(matrix_editor)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_12)
        self.groupBox_2 = QtGui.QGroupBox(matrix_editor)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.axisYComboBox = QtGui.QComboBox(self.groupBox_2)
        self.axisYComboBox.setObjectName("axisYComboBox")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.axisYComboBox)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_10)
        self.axisYAddrEdit = QtGui.QLineEdit(self.groupBox_2)
        self.axisYAddrEdit.setObjectName("axisYAddrEdit")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.axisYAddrEdit)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.countYEdit = QtGui.QLineEdit(self.groupBox_2)
        self.countYEdit.setObjectName("countYEdit")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.countYEdit)
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.groupBox_2)
        self.label_7 = QtGui.QLabel(matrix_editor)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.commentEdit = QtGui.QTextEdit(matrix_editor)
        self.commentEdit.setObjectName("commentEdit")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.commentEdit)
        self.okButton = QtGui.QPushButton(matrix_editor)
        self.okButton.setObjectName("okButton")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.okButton)
        self.cancelButton = QtGui.QPushButton(matrix_editor)
        self.cancelButton.setObjectName("cancelButton")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.cancelButton)
        self.label_13 = QtGui.QLabel(matrix_editor)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_13)
        self.funcEdit = QtGui.QLineEdit(matrix_editor)
        self.funcEdit.setObjectName("funcEdit")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.funcEdit)
        self.horizontalLayout.addLayout(self.formLayout)

        self.retranslateUi(matrix_editor)
        QtCore.QMetaObject.connectSlotsByName(matrix_editor)

    def retranslateUi(self, matrix_editor):
        matrix_editor.setWindowTitle(QtGui.QApplication.translate("matrix_editor", "matrix editor", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("matrix_editor", "Наименование таблицы:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("matrix_editor", "Размерность элемента:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("matrix_editor", "Адрес калибровки:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("matrix_editor", "Ось X:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("matrix_editor", "Тип оси Х:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("matrix_editor", "Адрес оси X:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("matrix_editor", "Кол-во элементов по оси X:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("matrix_editor", "Ось Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("matrix_editor", "Тип оси Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("matrix_editor", "Адрес оси Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("matrix_editor", "Кол-во элементов по оси Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("matrix_editor", "Комментарий:", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("matrix_editor", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("matrix_editor", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("matrix_editor", "Функция преобразования:", None, QtGui.QApplication.UnicodeUTF8))

